server :
   port: 12347
   servlet:
      context-path: /micro-calculator-service
      
spring:
  application:
    name: micro-calculator-service
      
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         #defaultZone: http://localhost:1234/eureka
         #defaultZone: http://localhost:1234/micro-eureka-service-discovery/eureka #non-docker
         defaultZone: http://docker-eureka-calculator-discovery:1234/micro-eureka-service-discovery/eureka #for docker communication
   instance:
      hostname: docker-micro-calculator-service #localhost-for non-docker
